version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: gscore_db
      POSTGRES_USER: gscore_user
      POSTGRES_PASSWORD: gscore_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: