version: '3.7'

services:

  postgres:
    image: 'postgres:15.4'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_DB: gscore_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456?A
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
